### ISSUE TITLE
Dataset not found

### ISSUE THREAD

**Issue by duxuan11** [ispras/angiocells_analysis#1]
When I clicked on the link, no results matched your search

**Comment by EKarpulevich** [comment]
![image](https://github.com/ispras/angiocells_analysis/assets/4557020/e381a6e7-4cf5-477b-b80b-3a1ad263224f)

**Comment by EKarpulevich** [comment]
> When I clicked on the link, no results matched your search

Hello, please check again. The link http://vessels.ispras.ru/ works for me.
But maybe you need russian VPN for access to this site, idk.
Here is the direct link to dataset: https://www.ispras.ru/conf/vessels/AngioCells.zip

**Comment by duxuan11** [comment]
Thank you for the response, I've already downloaded it.
